name: Feature Flags Workflow

on:
  push:
    branches: [ master]

  pull_request:
    types: [ opened, synchronize, reopned ]
    branches: [ master ]


jobs:

  validate:
    name: Validate Feature Flag
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 12.4.0

      - name: Install NPM Packages
        run: npm ci

      - name: Validate Flags
        run: npm run validate

      - name: Generate Combined TSV
        id: tsv
        run: npm run tsv

      - name: Commit Generated Flag TSV
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f generated/flags.tsv
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Updating flags TSV"
            git push
          fi

  artifact:
    name: Deploy Artifacts To AWS
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/master'

    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 12.4.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.28

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install NPM Packages
        run: npm ci --production

      - name: Zip Lambda Function
        run: zip -r terraform/ff.zip index.js constants.js node_modules flags

      - name: Deploy
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
